### ISSUE TITLE
Thanks!!

### ISSUE THREAD

**Issue by robouden** [HarryVienna/ESP32-S3-7-Inch-Display-LVGL#1]
After hours of researching, I finally came across your repo and could get the MaTouch ESP32-S3 working with VSCode/PlatformIO. What a blessing with all the information you shared on your website and in the repo.

I wish the makers/developers of that display would have made better examples on how to use /program it. Even the examples they have on GitHub did not work for me with Arduino IDE.

Regards
Rob Oudendijk

**Comment by HarryVienna** [comment]
Thank you very much Rob  :-)

I'm happy that the code is useful for you!

Cheers
Harald

**Comment by HarryVienna** [comment]
Thank you very much Rob :-)

I'm happy that the code is useful for you!

Cheers
Harald

**Comment by robouden** [comment]
Harald,

I hope you are doing fine.

Your code works very nice with the older boards. The new board (7 inch advanced see [this link](https://www.elecrow.com/pub/wiki/ESP32_Display-7.0_inch%28Advance_Series%29wiki.html)) seems to crash all the time. I mapped the display data pins to reflect the changes in the board GIO pins. But that did not help.

Any suggestions/test I can make to get this new board working?

Warm Regards
Rob
